# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  default-executor:
    machine:
      image: ubuntu-1604:201903-01
  node-executor:
    docker:
      - image: circleci/node:latest
jobs:
  build:
    # Use dedicated machine for testcontainer
    # https://www.testcontainers.org/supported_docker_environment/continuous_integration/circle_ci
    executor: default-executor
    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline --fail-never

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn integration-test

      - store_test_results:
          path: target/surefire-reports
  build-site:
    executor: node-executor

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build and Deploy Site
          command: ./build-deploy-site.sh
workflows:
  version: 2
  ci_build:
    jobs:
      - build
      - build-site:
          filters:
            branches:
              only: master
          requires:
            - build