name: Docker Builds
on:
  push:
    branches:
      - master
      - main
jobs:
  build_docker_image:
    if: github.repository == 'streamthoughts/kafka-connect-file-pulse'
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw clean package -B -Dmaven.test.skip=true;

      - name: Set env PROJECT_VERSION
        run: echo "PROJECT_VERSION=$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Check PROJECT_VERSION
        run: echo "${{ env.PROJECT_VERSION }}"

      - name: Set env GIT_BRANCH
        run: echo "GIT_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check GIT_BRANCH
        run: echo "${{ env.GIT_BRANCH }}"

      - name: Set GIT_COMMIT
        run: echo "GIT_COMMIT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Check GIT_COMMIT
        run: echo "${{ env.GIT_COMMIT }}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: streamthoughts/kafka-connect-file-pulse:master
          build-args: |
            connectFilePulseVersion=${{ env.PROJECT_VERSION }}
            connectFilePulseCommit=${{ env.GIT_COMMIT }}
            connectFilePulseBranch=${{ env.GIT_BRANCH }}